#!/bin/bash
#ffmpeg -hwaccel auto -i -c:v libsvtav1 -vf "scale=1920:1080" -preset 10 -crf 40 -c:a libvorbis

MODE="$1"
shift

case "$MODE" in
	--help|-h)
		echo "Usage: $0 <mode> [files...]"
		echo
		echo "Available modes: av1_40, av1_40_FHD, av1_40_FHD_scale, av1_40_FHD_scale_l"
		exit 0
		;;
	av1_40)
		export COMMAND=(-c:v libsvtav1 -preset 10 -crf 40 -c:a libvorbis)
		;;
	av1_40_FHD)
		export COMMAND=(-c:v libsvtav1 -vf "scale='if(gt(iw,1920) * gt(ih,1080),1920,-1)':'if(gt(iw,1920) * gt(ih,1080),-1,1080)'" -preset 10 -crf 40 -c:a libvorbis)	
		;;
	av1_40_FHD_scale)
		export COMMAND=(-c:v libsvtav1 -vf "scale='if(gt(iw,1920) * gt(ih,1080),if(gt(iw/1920,ih/1080),ceil(iw*1080/ih/2)*2, 1920),iw)':'if(gt(iw,1920) * gt(ih,1080),if(gt(iw/1920,ih/1080),1080,ceil(ih*1920/iw/2)*2),ih)'" -preset 10 -crf 40 -c:a libvorbis)	
		;;
	av1_40_FHD_scale_l)
		export COMMAND=(-c:v libsvtav1 -vf "scale='if(gt(iw,1920) * gt(ih,1080),if(gt(iw/1920,ih/1080),1920,ceil(iw*1080/ih/2)*2),iw)':'if(gt(iw,1920) * gt(ih,1080),if(gt(iw/1920,ih/1080),ceil(ih*1920/iw/2)*2,1080),ih)'" -preset 10 -crf 40 -c:a libvorbis)	
		;;
	*)
		echo "Incorrect mode" 1>&2
		exit 1
		;;
esac

HWACCEL="-hwaccel auto"

trap "export INT=1; kill -INT %1" SIGINT
SKIPPED=()

for i in "$@"; do
	INPUT="$i"
	OUTPUT="$(echo -n "$INPUT" | sed -z 's/\.[^\.\/]\+$\|$/.mkv/')"
	TEMP_OUTPUT="$(echo -n "$INPUT" | sed -z 's/[^\/]*$//').$(echo -n \"$INPUT\" | md5sum | head -c32).mkv"

	# DEBUG
	# echo "$INPUT"
	# echo "$OUTPUT"
	# echo "$TEMP_OUTPUT"
	# continue

	ffmpeg $HWACCEL -i "$INPUT" "${COMMAND[@]}" "$TEMP_OUTPUT"
	OUT="$?"
	if [ "$INT" != "" ]; then
		rm "$TEMP_OUTPUT" 2>/dev/null
		exit 1
	fi

	if [ "$OUT" == "0" ]; then
		mv "$INPUT" "${INPUT}.old"
		mv "$TEMP_OUTPUT" "$OUTPUT"
	else
		rm "$TEMP_OUTPUT" 2>/dev/null
		SKIPPED+=("$INPUT")
	fi
done

echo '-------- FINISHED --------'
[ "${#SKIPPED[@]}" != "0" ] && printf '%s\n' "Skipped videos:" "${SKIPPED[@]}"
