#!/bin/bash
#ffmpeg -hwaccel auto -i -c:v libsvtav1 -vf "scale=1920:1080" -preset 10 -crf 40 -c:a libvorbis

# Scaling filters
# Scales video to desired resolution without stretching, with option of allowing one axis greater then chosen
#
# Args:	_OW=...; _OH=...	Resolution (e.g. 1920:1080)
# _OW >= _OH, vertical videos supported
#
# Greater axis
# _SCALE="scale='if(gt(a,1),$_OW,$_OH)':'if(gt(a,1),$_OH,$_OW)':force_original_aspect_ratio=increase:force_divisible_by=2"
#
# Lesser axis
# _SCALE="scale='if(gt(a,1),$_OW,$_OH)':'if(gt(a,1),$_OH,$_OW)':force_original_aspect_ratio=decrease:force_divisible_by=2"
#

MODE="$1"
shift

case "$MODE" in
	--help|-h)
		echo "Usage: $0 <mode> [files...]"
		echo
		echo "Available modes: av1_40, av1_40_FHD, av1_40_FHD_scale, av1_40_FHD_scale_l"
		exit 0
		;;
	av1_40)
		COMMAND=(-c:v libsvtav1 -preset 10 -crf 40 -c:a libvorbis)
		;;
	av1_40_FHD)
		COMMAND=(-c:v libsvtav1 -vf "scale='if(gt(iw,1920) + gt(ih,1080),1920,-1)':'if(gt(iw,1920) + gt(ih,1080),-1,1080)'" -preset 10 -crf 40 -c:a libvorbis)	
		;;
	av1_40_FHD_scale)
		_OW=1920; _OH=1080
		_SCALE="scale='if(gt(a,1),if(gt(iw,$_OW)+gt(ih,$_OH),$_OW,iw),if(gt(iw,$_OH)+gt(ih,$_OW),$_OH,iw))':'if(gt(a,1),if(gt(iw,$_OW)+gt(ih,$_OH),$_OH,ih),if(gt(iw,$_OH)+gt(ih,$_OW),$_OW,ih))':force_original_aspect_ratio=increase:force_divisible_by=2"

		COMMAND=(-c:v libsvtav1 -vf "$_SCALE" -preset 10 -crf 40 -c:a libvorbis)	
		;;
	av1_40_FHD_scale_l)
		_OW=1920; _OH=1080
		_SCALE="scale='if(gt(a,1),if(gt(iw,$_OW)+gt(ih,$_OH),$_OW,iw),if(gt(iw,$_OH)+gt(ih,$_OW),$_OH,iw))':'if(gt(a,1),if(gt(iw,$_OW)+gt(ih,$_OH),$_OH,ih),if(gt(iw,$_OH)+gt(ih,$_OW),$_OW,ih))':force_original_aspect_ratio=decrease:force_divisible_by=2"

		COMMAND=(-c:v libsvtav1 -vf "$_SCALE" -preset 10 -crf 40 -c:a libvorbis)	
		;;
	*)
		echo "Incorrect mode" 1>&2
		exit 1
		;;
	# Add custom entries here
esac

HWACCEL="-hwaccel auto"

trap "export INT=1; kill -INT %1" SIGINT
SKIPPED=()

for i in "$@"; do
	INPUT="$i"
	OUTPUT="$(echo -n "$INPUT" | sed -z 's/\.[^\.\/]\+$\|$/.mkv/')"
	TEMP_OUTPUT="$(echo -n "$INPUT" | sed -z 's/[^\/]*$//').$(echo -n \"$INPUT\" | md5sum | head -c32).mkv"

	# DEBUG
	# echo "$INPUT"
	# echo "$OUTPUT"
	# echo "$TEMP_OUTPUT"
	# continue

	ffmpeg $HWACCEL -i "$INPUT" "${COMMAND[@]}" "$TEMP_OUTPUT"
	OUT="$?"
	if [ "$INT" != "" ]; then
		rm "$TEMP_OUTPUT" 2>/dev/null
		exit 1
	fi

	if [ "$OUT" == "0" ]; then
		mv "$INPUT" "${INPUT}.old"
		mv "$TEMP_OUTPUT" "$OUTPUT"
	else
		rm "$TEMP_OUTPUT" 2>/dev/null
		SKIPPED+=("$INPUT")
	fi
done

echo '-------- FINISHED --------'
[ "${#SKIPPED[@]}" != "0" ] && printf '%s\n' "Skipped videos:" "${SKIPPED[@]}"
