#!/bin/bash
trap "kill -INT %1" SIGINT

for i in "$@"; do
	INPUT="$i"
	OUTPUT="$(echo -n "$INPUT" | sed -z 's/\.[^\/]\+$\|$/.mkv/')"
	TEMP_OUTPUT="$(echo -n "$INPUT" | sed 's/[^\/]*$//').$(echo -n \"$INPUT\" | md5sum | head -c32).mkv"
	#echo $INPUT
	#echo $OUTPUT
	#echo $TEMP_OUTPUT
	#read -p 'Continue? '

	ffmpeg $HWACCEL -i "$INPUT" $COMMAND "$TEMP_OUTPUT"
	if [ "$?" == "0" ]; then
		mv "$INPUT" "${INPUT}.old"

		#read -p "Delete original file? " choice
		#case $choice in
		#	y|Y)
		#		#rm "$INPUT"
		#		;;
		#	n|N)
		#		mv "$INPUT" "${INPUT}.old"
		#		;;
		#esac

		mv "$TEMP_OUTPUT" "$OUTPUT"
	else
		rm "$TEMP_OUTPUT" 2>/dev/null
		read -p "ERROR, press any key to exit..."
		exit 1
	fi
done

